### ISSUE TITLE
'BlazorScheduler' was undefined

### ISSUE THREAD

**Issue by rgry** [valincius/BlazorScheduler#52]
**Describe the bug**
Properly not a bug, just me not understanding how to get started.
Your project solution work fine. But when I do a new project and follow the few step from the readme file the blazor app is not running proberly. It compiles without errors. Only runtime error
I did not copy the scripts.js to a folder? is your package doing that for me?

**To Reproduce**
New blazor webasm project.
steps from readme
(and I did Add <script src="_content/BlazorScheduler/js/scripts.js"></script> to the body 

**Expected behavior**
Was not expecting "crash" on page

**Screenshots**
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'BlazorScheduler.attachSchedulerMouseEventsHandler' ('BlazorScheduler' was undefined).
      Error: Could not find 'BlazorScheduler.attachSchedulerMouseEventsHandler' ('BlazorScheduler' was undefined).
          at https://localhost:4201/_framework/blazor.webassembly.js:1:328
          at Array.forEach (<anonymous>)
          at a.findFunction (https://localhost:4201/_framework/blazor.webassembly.js:1:296)
          at _ (https://localhost:4201/_framework/blazor.webassembly.js:1:2437)
          at https://localhost:4201/_framework/blazor.webassembly.js:1:3325
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:4201/_framework/blazor.webassembly.js:1:3306)
          at Object.St [as invokeJSFromDotNet] (https://localhost:4201/_framework/blazor.webassembly.js:1:59853)
          at _mono_wasm_invoke_js_blazor (https://localhost:4201/_framework/dotnet.6.0.5.7ue9mewvww.js:1:195300)
          at wasm://wasm/00971e46:wasm-function[219]:0x1a490
Microsoft.JSInterop.JSException: Could not find 'BlazorScheduler.attachSchedulerMouseEventsHandler' ('BlazorScheduler' was undefined).
Error: Could not find 'BlazorScheduler.attachSchedulerMouseEventsHandler' ('BlazorScheduler' was undefined).
    at https://localhost:4201/_framework/blazor.webassembly.js:1:328
    at Array.forEach (<anonymous>)
    at a.findFunction (https://localhost:4201/_framework/blazor.webassembly.js:1:296)
    at _ (https://localhost:4201/_framework/blazor.webassembly.js:1:2437)
    at https://localhost:4201/_framework/blazor.webassembly.js:1:3325
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:4201/_framework/blazor.webassembly.js:1:3306)
    at Object.St [as invokeJSFromDotNet] (https://localhost:4201/_framework/blazor.webassembly.js:1:59853)
    at _mono_wasm_invoke_js_blazor (https://localhost:4201/_framework/dotnet.6.0.5.7ue9mewvww.js:1:195300)
    at wasm://wasm/00971e46:wasm-function[219]:0x1a490
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at BlazorScheduler.Scheduler.AttachMouseHandler() in C:\Users\rune\Documents\Visual Studio 2022\BlazorScheduler-main\BlazorScheduler\Components\Scheduler.razor.cs:line 120
   at BlazorScheduler.Scheduler.OnAfterRenderAsync(Boolean firstRender) in C:\Users\rune\Documents\Visual Studio 2022\BlazorScheduler-main\BlazorScheduler\Components\Scheduler.razor.cs:line 82
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Desktop (please complete the following information):**
 - OS: Win10x64
 - Browser Edge 101

**Comment by valincius** [comment]
Sounds like you've got it setup properly. Have you tried clearing your cache ?

**Comment by rgry** [comment]
Thank you Valincius, that did the trick!
How to you handle cache in your projects? How to tell the browser, that a new/updated project is loaded?

kind regards
Rune

**Comment by kacperkwietniewski** [comment]
Hello,
i have same problem with importing css and js files.

**App specs:**

- Windows 11
- Blazor web app 
- .NET 9
- BlazorScheduler 4.3.3


**Describe the bug:**
The JavaScript and CSS file does not load at startup; after reloading the cache, it appears but is empty. This issue occurs every time the application starts, requiring the cache to be cleared.

Before clean:
![Image](https://github.com/user-attachments/assets/a8b9fb1a-0a8a-43b4-b3cb-d5370b83f56b)
After:
![Image](https://github.com/user-attachments/assets/5eea547a-094f-41a9-bf79-e07631a50caa)

![Image](https://github.com/user-attachments/assets/2713e8fe-faa5-4a77-ba4b-66f255d67d14)

![Image](https://github.com/user-attachments/assets/bae349b1-33f4-4b56-afaf-78a1afc82747)

**To Reproduce:**
Install newest version of BlazorScheduler from NuGet
Include packages (.NET 9 way with @Assets[]).
<.head.>
    <base href="/" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0" />

    <link rel="stylesheet" href="@Assets["_content/BlazorScheduler/css/styles.css"]" />
    <link rel="stylesheet" href="@Assets["_content/MudBlazor/MudBlazor.min.css"]" />
    …
    <HeadOutlet @rendermode="new InteractiveWebAssemblyRenderMode(prerender: false)" />
    <ImportMap />
</.head.>


<.body.>
    <Routes @rendermode="new InteractiveWebAssemblyRenderMode(prerender: false)" />
    …
    <script src="_framework/blazor.web.js"></script>
    <script src="@Assets["_content/BlazorScheduler/js/scripts.js"]"></script>
    …
</.body.>

**Expected behavior:**
App runs without error.


**Error message:**
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'BlazorScheduler.attachSchedulerMouseEventsHandler' ('BlazorScheduler' was undefined).
      Error: Could not find 'BlazorScheduler.attachSchedulerMouseEventsHandler' ('BlazorScheduler' was undefined).
          at http://127.0.0.1:4500/_framework/blazor.web.js:1:384
          at Array.forEach (<anonymous>)
          at l.findFunction (http://127.0.0.1:4500/_framework/blazor.web.js:1:352)
          at _ (http://127.0.0.1:4500/_framework/blazor.web.js:1:5101)
          at http://127.0.0.1:4500/_framework/blazor.web.js:1:2894
          at new Promise (<anonymous>)
          at w.beginInvokeJSFromDotNet (http://127.0.0.1:4500/_framework/blazor.web.js:1:2857)
          at Object.jr [as invokeJSJson] (http://127.0.0.1:4500/_framework/blazor.web.js:1:165356)
          at http://127.0.0.1:4500/_framework/dotnet.runtime.tsg4gsv2hg.js:3:33879
          at Fc (http://127.0.0.1:4500/_framework/dotnet.runtime.tsg4gsv2hg.js:3:172155)
Microsoft.JSInterop.JSException: Could not find 'BlazorScheduler.attachSchedulerMouseEventsHandler' ('BlazorScheduler' was undefined).
Error: Could not find 'BlazorScheduler.attachSchedulerMouseEventsHandler' ('BlazorScheduler' was undefined).
    at http://127.0.0.1:4500/_framework/blazor.web.js:1:384
    at Array.forEach (<anonymous>)
    at l.findFunction (http://127.0.0.1:4500/_framework/blazor.web.js:1:352)
    at _ (http://127.0.0.1:4500/_framework/blazor.web.js:1:5101)
    at http://127.0.0.1:4500/_framework/blazor.web.js:1:2894
    at new Promise (<anonymous>)
    at w.beginInvokeJSFromDotNet (http://127.0.0.1:4500/_framework/blazor.web.js:1:2857)
    at Object.jr [as invokeJSJson] (http://127.0.0.1:4500/_framework/blazor.web.js:1:165356)
    at http://127.0.0.1:4500/_framework/dotnet.runtime.tsg4gsv2hg.js:3:33879
    at Fc (http://127.0.0.1:4500/_framework/dotnet.runtime.tsg4gsv2hg.js:3:172155)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at BlazorScheduler.Scheduler.AttachMouseHandler()
   at BlazorScheduler.Scheduler.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
